spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nombre_de_tu_base_de_datos
    username: usuario_de_la_base_de_datos
    password: contraseña_de_la_base_de_datos
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
